name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code using the latest version of checkout
      - name: Checkout code
        uses: actions/checkout@v3  # Using v3, as v2 might be restricted

      # Step 2: Install Node.js manually (skip if preinstalled on the runner)
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -  # Install Node.js 16
          sudo apt-get install -y nodejs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --force

      # Step 4: Build the React app
      - name: Build the React app
        run: npm run build

      # Step 5: Deploy to GitHub Pages (push to gh-pages of username.github.io repository)
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
