name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Build the project
        run: npm run build

      - name: Remove symlinks and files with more than one hard link from the dist folder
        run: |
          # Find and remove symlinks in the dist directory
          find ./dist -type l -exec rm -f {} \;
          # Find and remove files with more than one hard link (i.e., hard links)
          find ./dist -type f -links +1 -exec rm -f {} \;

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4
        with:
          # Point to the folder to deploy from (e.g., 'dist' folder)
          path: './dist'

      - name: Deploy to GitHub Pages (final step)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Point to the same folder
          path: './dist'
