name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Manually checkout the repository using Git
      - name: Checkout code manually
        run: |
          git clone https://github.com/${{ github.repository }} .
          git fetch --all
          git checkout main

      # Step 2: Install Node.js (install manually)
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v  # Verify Node.js installation
          npm -v   # Verify npm installation

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --force

      # Step 4: Build the React app
      - name: Build the React app
        run: npm run build

      # Step 5: Deploy to GitHub Pages (push to gh-pages of username.github.io repository)
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
