name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Node.js
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v  # Verify Node.js installation
          npm -v   # Verify npm installation

      # Step 3: Install Yarn
      - name: Install Yarn
        run: |
          npm install -g yarn  # Install Yarn globally
          yarn -v  # Verify Yarn installation

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install --force

      # Step 5: Build the React app (this will generate the 'dist' folder)
      - name: Build the React app
        run: yarn build

      # Step 6: Set up GitHub Pages deployment using GitHub token
      - name: Deploy to GitHub Pages using npx
        run: |
          # Use npx to deploy the contents of the 'build' folder to gh-pages
          npx gh-pages -d build -b gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
