name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v  # Verify Node.js installation
          npm -v   # Verify npm installation

      # Step 3: Install Yarn
      - name: Install Yarn
        run: |
          npm install -g yarn  # Install Yarn globally
          yarn -v  # Verify Yarn installation

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install --force

      # Step 5: Build the React app (this will generate the 'dist' folder)
      - name: Build the React app
        run: yarn build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          # Create a new branch gh-pages (if not exists) and push the content of 'dist' folder
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check out the gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard

          # Copy files from the dist folder (build output) to the root of gh-pages
          cp -a dist/. .

          # Add, commit, and push changes to the gh-pages branch
          git add --all
          git commit -m "Deploy React app to GitHub Pages"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
